#!/usr/bin/env bash
# End-to-end walk through all four planes against a real cluster.
#
#   artifact       images built and pushed, digests captured from the registry
#   contract       site values validated against values.schema.json
#   distribution   chart and images mirrored into a registry the cluster can reach
#   reconciliation | Argo CD pulls the resolved version; nothing is pushed at it
#
set -euo pipefail

CLUSTER=${CLUSTER:-exclave-demo}
REG_NAME=${REG_NAME:-exclave-registry}
REG_PORT=${REG_PORT:-5001}
CTX="kind-${CLUSTER}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"

say() { printf '\n\033[1m== %s\033[0m\n' "$*"; }

# ─────────────────────────────── registry ───────────────────────────────
say "local registry"
if [ "$(docker inspect -f '{{.State.Running}}' "$REG_NAME" 2>/dev/null || true)" != "true" ]; then
  docker run -d --restart=always -p "127.0.0.1:${REG_PORT}:5000" \
    --name "$REG_NAME" registry:2 >/dev/null
  echo "started $REG_NAME on :$REG_PORT"
else
  echo "$REG_NAME already running"
fi

# ─────────────────────────────── cluster ───────────────────────────────
say "kind cluster"
if ! kind get clusters 2>/dev/null | grep -qx "$CLUSTER"; then
  cat <<EOF | kind create cluster --name "$CLUSTER" --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
EOF
  # Point the nodes at the local registry for anything tagged localhost:5001.
  for node in $(kind get nodes --name "$CLUSTER"); do
    docker exec "$node" mkdir -p "/etc/containerd/certs.d/localhost:${REG_PORT}"
    docker exec -i "$node" cp /dev/stdin "/etc/containerd/certs.d/localhost:${REG_PORT}/hosts.toml" <<EOF
[host."http://${REG_NAME}:5000"]
  capabilities = ["pull", "resolve"]
EOF
  done
else
  echo "cluster $CLUSTER already exists"
fi

# The registry has to sit on the kind network so both the nodes and Argo CD's
# repo-server can reach it by name.
docker network connect kind "$REG_NAME" 2>/dev/null || true

# ───────────────────── plane 1: artifact ─────────────────────
say "plane 1 — build, push, capture real digests"
declare -A DIGEST
for svc in auth-svc billing-svc; do
  docker build -q \
    --build-arg "SERVICE=${svc}" --build-arg "VERSION=${TARGET_VERSION:-3.2.0}" \
    -t "localhost:${REG_PORT}/acme/${svc}:dev" "$HERE/services/svc" >/dev/null
  docker push -q "localhost:${REG_PORT}/acme/${svc}:dev" >/dev/null
  # The digest is read back from the registry, never hand-written. A release
  # manifest that claims a digest nobody verified is worse than no digest.
  d=$(docker inspect --format='{{index .RepoDigests 0}}' "localhost:${REG_PORT}/acme/${svc}:dev" | cut -d@ -f2)
  DIGEST[$svc]=$d
  echo "  ${svc}  ${d}"
done

# ───────────────────── plane 2: contract ─────────────────────
say "plane 2 — site values, schema-validated"
SITE="$HERE/.demo/site-values.yaml"
mkdir -p "$HERE/.demo"
cat > "$SITE" <<EOF
# Generated by demo.sh from what was actually built.
global:
  registry: "localhost:${REG_PORT}"
  product: acme-platform
auth-svc:
  image:
    repository: acme/auth-svc
    digest: "${DIGEST[auth-svc]}"
    tag: ""
  replicas: 1
billing-svc:
  image:
    repository: acme/billing-svc
    digest: "${DIGEST[billing-svc]}"
    tag: ""
  replicas: 1
EOF
helm dependency update "$HERE/charts/product" >/dev/null
helm template acme "$HERE/charts/product" -f "$SITE" >/dev/null
echo "  values validated against values.schema.json"

# ───────────────────── plane 4: resolve ─────────────────────
say "plane 4 — which release does each environment get?"
( cd "$ROOT" && go run ./cmd/exclave plan \
    -catalog "$HERE/catalog" -fleet "$HERE/fleet/environments" )

TARGET=$( cd "$ROOT" && go run ./cmd/exclave plan \
    -catalog "$HERE/catalog" -fleet "$HERE/fleet/environments" \
    | awk '$1=="customer-a-prod"{print $3}' )
echo
echo "  customer-a-prod resolves to ${TARGET} — that is what gets installed below."

# ───────────────────── plane 3: distribution ─────────────────────
say "plane 3 — publish the product chart to the registry"
helm package "$HERE/charts/product" --version "$TARGET" --app-version "$TARGET" \
  -d "$HERE/.demo" >/dev/null
helm push "$HERE/.demo/acme-platform-${TARGET}.tgz" \
  "oci://localhost:${REG_PORT}/charts" --plain-http 2>&1 | sed 's/^/  /'

# ───────────────────── plane 4: reconciliation ─────────────────────
say "plane 4 — Argo CD pulls it. Nothing is pushed at the cluster."
# Argo CD's controllers cache DNS failures on startup, so do not install them
# until the cluster is actually serving DNS.
kubectl --context "$CTX" -n kube-system rollout status deploy/coredns --timeout=180s >/dev/null
kubectl --context "$CTX" wait --for=condition=Ready pods -n kube-system --all --timeout=180s >/dev/null

kubectl --context "$CTX" create namespace argocd --dry-run=client -o yaml | kubectl --context "$CTX" apply -f - >/dev/null
if ! kubectl --context "$CTX" -n argocd get deploy argocd-repo-server >/dev/null 2>&1; then
  echo "  installing Argo CD (this is the slow step)..."
  # Server-side apply: the ApplicationSet CRD exceeds the 256KB limit on the
  # last-applied-configuration annotation that client-side apply writes.
  kubectl --context "$CTX" -n argocd apply --server-side --force-conflicts -f \
    https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml >/dev/null
fi
kubectl --context "$CTX" -n argocd rollout status deploy/argocd-repo-server --timeout=300s
kubectl --context "$CTX" -n argocd rollout status deploy/argocd-applicationset-controller --timeout=300s

kubectl --context "$CTX" apply -f - <<EOF >/dev/null
apiVersion: v1
kind: Secret
metadata:
  name: acme-charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: acme-charts
  url: ${REG_NAME}:5000/charts
  enableOCI: "true"
  insecure: "true"
EOF

kubectl --context "$CTX" create namespace acme --dry-run=client -o yaml | kubectl --context "$CTX" apply -f - >/dev/null
kubectl --context "$CTX" apply -f - <<EOF >/dev/null
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acme-platform-customer-a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${REG_NAME}:5000/charts
    chart: acme-platform
    targetRevision: "${TARGET}"
    helm:
      values: |
$(sed 's/^/        /' "$SITE")
  destination:
    server: https://kubernetes.default.svc
    namespace: acme
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
EOF

echo "  waiting for the agent to converge..."
sync=""
for i in $(seq 1 48); do
  sync=$(kubectl --context "$CTX" -n argocd get application acme-platform-customer-a \
           -o jsonpath='{.status.sync.status}' 2>/dev/null || true)
  [ "$sync" = "Synced" ] && break
  sleep 5
done

if [ "$sync" != "Synced" ]; then
  # Argo CD's gRPC between its controller and repo-server is unreliable on some
  # local Docker backends. That is a property of this laptop, not of the design,
  # so fall back to installing the same OCI chart at the same resolved version
  # rather than pretending the run failed. Planes 1-3 are unaffected either way.
  cat >&2 <<'WARN'

  Argo CD did not converge. Its condition:
WARN
  kubectl --context "$CTX" -n argocd get application acme-platform-customer-a \
    -o jsonpath='{.status.conditions[*].message}' >&2 || true
  cat >&2 <<'WARN'

  Falling back to a direct install of the same chart at the same version.
  The pull-based path is what you would run for real; this keeps the demo
  honest about what did and did not happen.

WARN
  helm install acme "oci://localhost:${REG_PORT}/charts/acme-platform" \
    --version "$TARGET" --plain-http -n acme --create-namespace \
    -f "$SITE" --wait --timeout 180s >/dev/null
  echo "  installed directly (Argo CD path skipped)"
fi

say "result"
kubectl --context "$CTX" -n argocd get application acme-platform-customer-a \
  -o custom-columns=NAME:.metadata.name,REVISION:.spec.source.targetRevision,SYNC:.status.sync.status,HEALTH:.status.health.status
echo
kubectl --context "$CTX" -n acme get deploy,pod -o wide 2>/dev/null | sed 's/^/  /'
echo
echo "Running images (digest-pinned, resolved through global.registry):"
kubectl --context "$CTX" -n acme get pods \
  -o jsonpath='{range .items[*]}  {.spec.containers[0].image}{"\n"}{end}'
